music_directory    "/home/max/music"
playlist_directory "/home/max/.config/mpd/playlists"
db_file            "/home/max/.config/mpd/database"
log_file           "/home/max/.config/mpd/log"
pid_file           "/home/max/.config/mpd/pid"
state_file         "/home/max/.config/mpd/state"

audio_output {
    type    "pulse"
    name    "PulseAudio"
}

filesystem_charset "UTF-8"
